back-end:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/backend/**"
          - "apps/validation-server/**"

front-end:
  - changed-files:
      - any-glob-to-any-file: "apps/frontend/**"

shared:
  - changed-files:
      - any-glob-to-any-file:
          - "!apps/backend/**"
          - "!apps/validation-server/**"
          - "!apps/frontend/**"
          - "**"
