back-end:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/backend/**"
          - "apps/validation-server/**"

front-end:
  - changed-files:
      - any-glob-to-any-file: "apps/frontend/**"

shared:
  - all:
      - changed-files:
          - any-glob-to-any-file: "**"
      - changed-files:
          - all-globs-to-all-files:
              - "!apps/backend/**"
              - "!apps/validation-server/**"
              - "!apps/frontend/**"
