back-end:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/backend/**"

front-end:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/frontend/**"
          - "apps/bff/**"

shared:
  - changed-files:
      - all-globs-to-any-file:
          - "!apps/backend/**"
          - "!apps/frontend/**"
          - "!apps/bff/**"
