steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/backend/api/Dockerfile
      - -t
      - asia-northeast3-docker.pkg.dev/$PROJECT_ID/schemafy/api:$_TAG
      - -t
      - asia-northeast3-docker.pkg.dev/$PROJECT_ID/schemafy/api:latest
      - .
images:
  - asia-northeast3-docker.pkg.dev/$PROJECT_ID/schemafy/api:$_TAG
  - asia-northeast3-docker.pkg.dev/$PROJECT_ID/schemafy/api:latest
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s
