spring:
  application:
    name: core
  config:
    activate:
      on-profile: server

  r2dbc:
    url: r2dbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:schemafy}
    username: ${DB_USER:schemafy}
    password: ${DB_PASSWORD:schemafy}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-jwt-token-generation-min-256-bits-required}
  access-token-expiration: 7200000
  refresh-token-expiration: 604800000
  issuer: schemafy-test
  audience: schemafy-test-audience

cors:
  allowed-origins: ${JWT_ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true