package com.schemafy.core.erd.service.util.mysql;

import java.time.Instant;
import java.util.List;

import org.springframework.stereotype.Component;

import com.schemafy.core.erd.controller.dto.response.SchemaDetailResponse;
import com.schemafy.core.erd.controller.dto.response.TableDetailResponse;
import com.schemafy.core.erd.service.util.DdlGenerator;

import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class MySqlDdlGenerator implements DdlGenerator {

  private final MySqlCreateTableGenerator createTableGenerator;
  private final MySqlAlterTableGenerator alterTableGenerator;

  @Override
  public String generateSchemaDdl(SchemaDetailResponse schema,
      List<TableDetailResponse> tables) {
    StringBuilder ddl = new StringBuilder();
    ddl.append(generateHeader(schema));

    for (TableDetailResponse table : tables) {
      ddl.append(createTableGenerator.generate(table));
      ddl.append("\n\n");
    }

    ddl.append(alterTableGenerator.generate(tables));

    return ddl.toString();
  }

  private String generateHeader(SchemaDetailResponse schema) {
    return "-- =============================================================================\n"
        + "-- Schema: " + schema.getName() + "\n"
        + "-- Exported: " + Instant.now() + "\n"
        + "-- Generated by Schemafy Export\n"
        + "-- =============================================================================\n\n";
  }

}
