package com.schemafy.core.erd.service.util.mysql;

import java.time.Instant;
import java.util.Collections;
import java.util.List;

import org.springframework.stereotype.Component;

import com.schemafy.core.erd.controller.dto.response.SchemaDetailResponse;
import com.schemafy.core.erd.controller.dto.response.TableDetailResponse;
import com.schemafy.core.erd.service.util.DdlGenerator;

import lombok.RequiredArgsConstructor;

@Component
@RequiredArgsConstructor
public class MySqlDdlGenerator implements DdlGenerator {

  private final MySqlCreateTableGenerator createTableGenerator;
  private final MySqlAlterTableGenerator alterTableGenerator;

  @Override
  public String generateSchemaDdl(SchemaDetailResponse schema,
      List<TableDetailResponse> tables) {
    StringBuilder ddl = new StringBuilder();
    ddl.append(generateHeader(schema));

    List<TableDetailResponse> safeTables = tables != null
        ? tables
        : Collections.emptyList();

    for (TableDetailResponse table : safeTables) {
      if (table == null) {
        continue;
      }
      ddl.append(createTableGenerator.generate(table));
      ddl.append("\n\n");
    }

    ddl.append(alterTableGenerator.generate(safeTables));

    return ddl.toString();
  }

  private String generateHeader(SchemaDetailResponse schema) {
    String schemaName = escapeComment(schema.getName());
    return "-- =============================================================================\n"
        + "-- Schema: " + schemaName + "\n"
        + "-- Exported: " + Instant.now() + "\n"
        + "-- Generated by Schemafy Export\n"
        + "-- =============================================================================\n\n";
  }

  private String escapeComment(String value) {
    if (value == null) {
      return "";
    }
    return value.replace("--", "- -").replace("\n", " ").replace("\r", " ");
  }

}
