package com.schemafy.core.erd.operation.application.inverse;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonSubTypes({
  @JsonSubTypes.Type(value = ChangeTableNameInverse.class, name = "CHANGE_TABLE_NAME"),
  @JsonSubTypes.Type(value = ChangeTableMetaInverse.class, name = "CHANGE_TABLE_META"),
  @JsonSubTypes.Type(value = ChangeTableExtraInverse.class, name = "CHANGE_TABLE_EXTRA"),
  @JsonSubTypes.Type(value = ChangeColumnNameInverse.class, name = "CHANGE_COLUMN_NAME"),
  @JsonSubTypes.Type(value = ChangeColumnTypeInverse.class, name = "CHANGE_COLUMN_TYPE"),
  @JsonSubTypes.Type(value = ChangeColumnMetaInverse.class, name = "CHANGE_COLUMN_META"),
  @JsonSubTypes.Type(value = ChangeRelationshipNameInverse.class, name = "CHANGE_RELATIONSHIP_NAME"),
  @JsonSubTypes.Type(value = ChangeRelationshipCardinalityInverse.class, name = "CHANGE_RELATIONSHIP_CARDINALITY"),
  @JsonSubTypes.Type(value = ChangeRelationshipExtraInverse.class, name = "CHANGE_RELATIONSHIP_EXTRA"),
  @JsonSubTypes.Type(value = ChangeConstraintNameInverse.class, name = "CHANGE_CONSTRAINT_NAME"),
  @JsonSubTypes.Type(value = ChangeConstraintCheckExprInverse.class, name = "CHANGE_CONSTRAINT_CHECK_EXPR"),
  @JsonSubTypes.Type(value = ChangeConstraintDefaultExprInverse.class, name = "CHANGE_CONSTRAINT_DEFAULT_EXPR"),
  @JsonSubTypes.Type(value = ChangeIndexNameInverse.class, name = "CHANGE_INDEX_NAME"),
  @JsonSubTypes.Type(value = ChangeIndexTypeInverse.class, name = "CHANGE_INDEX_TYPE"),
  @JsonSubTypes.Type(value = ChangeIndexColumnSortDirectionInverse.class, name = "CHANGE_INDEX_COLUMN_SORT_DIRECTION"),
  @JsonSubTypes.Type(value = CreateTableInverse.class, name = "CREATE_TABLE"),
  @JsonSubTypes.Type(value = DeleteTableInverse.class, name = "DELETE_TABLE"),
  @JsonSubTypes.Type(value = CreateColumnInverse.class, name = "CREATE_COLUMN"),
  @JsonSubTypes.Type(value = DeleteColumnInverse.class, name = "DELETE_COLUMN"),
  @JsonSubTypes.Type(value = CreateConstraintInverse.class, name = "CREATE_CONSTRAINT"),
  @JsonSubTypes.Type(value = DeleteConstraintInverse.class, name = "DELETE_CONSTRAINT"),
  @JsonSubTypes.Type(value = AddConstraintColumnInverse.class, name = "ADD_CONSTRAINT_COLUMN"),
  @JsonSubTypes.Type(value = RemoveConstraintColumnInverse.class, name = "REMOVE_CONSTRAINT_COLUMN"),
  @JsonSubTypes.Type(value = CreateIndexInverse.class, name = "CREATE_INDEX"),
  @JsonSubTypes.Type(value = DeleteIndexInverse.class, name = "DELETE_INDEX"),
  @JsonSubTypes.Type(value = AddIndexColumnInverse.class, name = "ADD_INDEX_COLUMN"),
  @JsonSubTypes.Type(value = RemoveIndexColumnInverse.class, name = "REMOVE_INDEX_COLUMN"),
  @JsonSubTypes.Type(value = CreateRelationshipInverse.class, name = "CREATE_RELATIONSHIP"),
  @JsonSubTypes.Type(value = ChangeRelationshipKindInverse.class, name = "CHANGE_RELATIONSHIP_KIND"),
  @JsonSubTypes.Type(value = DeleteRelationshipInverse.class, name = "DELETE_RELATIONSHIP"),
  @JsonSubTypes.Type(value = AddRelationshipColumnInverse.class, name = "ADD_RELATIONSHIP_COLUMN"),
  @JsonSubTypes.Type(value = RemoveRelationshipColumnInverse.class, name = "REMOVE_RELATIONSHIP_COLUMN")
})
public sealed interface InversePayload permits
    ChangeTableNameInverse,
    ChangeTableMetaInverse,
    ChangeTableExtraInverse,
    ChangeColumnNameInverse,
    ChangeColumnTypeInverse,
    ChangeColumnMetaInverse,
    ChangeRelationshipNameInverse,
    ChangeRelationshipCardinalityInverse,
    ChangeRelationshipExtraInverse,
    ChangeConstraintNameInverse,
    ChangeConstraintCheckExprInverse,
    ChangeConstraintDefaultExprInverse,
    ChangeIndexNameInverse,
    ChangeIndexTypeInverse,
    ChangeIndexColumnSortDirectionInverse,
    CreateTableInverse,
    DeleteTableInverse,
    CreateColumnInverse,
    DeleteColumnInverse,
    CreateConstraintInverse,
    DeleteConstraintInverse,
    AddConstraintColumnInverse,
    RemoveConstraintColumnInverse,
    CreateIndexInverse,
    DeleteIndexInverse,
    AddIndexColumnInverse,
    RemoveIndexColumnInverse,
    CreateRelationshipInverse,
    ChangeRelationshipKindInverse,
    DeleteRelationshipInverse,
    AddRelationshipColumnInverse,
    RemoveRelationshipColumnInverse {

}
