package com.schemafy.domain.project.domain.exception;

import org.springframework.http.HttpStatus;

import com.schemafy.domain.common.exception.DomainErrorCode;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ProjectErrorCode implements DomainErrorCode {

  NOT_FOUND(HttpStatus.NOT_FOUND),
  ACCESS_DENIED(HttpStatus.FORBIDDEN),
  OWNER_ONLY(HttpStatus.FORBIDDEN),
  ADMIN_REQUIRED(HttpStatus.FORBIDDEN),
  WORKSPACE_MISMATCH(HttpStatus.BAD_REQUEST),
  SETTINGS_TOO_LARGE(HttpStatus.BAD_REQUEST),
  ALREADY_DELETED(HttpStatus.CONFLICT),
  CANNOT_ASSIGN_HIGHER_ROLE(HttpStatus.FORBIDDEN),
  CANNOT_MODIFY_HIGHER_ROLE_MEMBER(HttpStatus.FORBIDDEN),
  CANNOT_CHANGE_OWN_ROLE(HttpStatus.FORBIDDEN),
  LAST_OWNER_CANNOT_BE_REMOVED(HttpStatus.BAD_REQUEST),
  WORKSPACE_MEMBERSHIP_REQUIRED(HttpStatus.FORBIDDEN),
  MEMBER_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST),
  MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND),
  MEMBER_ALREADY_EXISTS(HttpStatus.CONFLICT),
  INVITATION_EMAIL_MISMATCH(HttpStatus.BAD_REQUEST),
  INVITATION_NOT_FOUND(HttpStatus.NOT_FOUND),
  INVITATION_DUPLICATE_WORKSPACE_MEMBER(HttpStatus.CONFLICT),
  INVITATION_EXPIRED(HttpStatus.BAD_REQUEST),
  WORKSPACE_INVITATION_ALREADY_PROCESSED(HttpStatus.CONFLICT),
  PROJECT_INVITATION_ALREADY_PROCESSED(HttpStatus.CONFLICT),
  INVITATION_CONCURRENT_PROCESSED(HttpStatus.CONFLICT),
  INVITATION_DUPLICATE_MEMBERSHIP_PROJECT(HttpStatus.CONFLICT),
  INVITATION_ALREADY_EXISTS(HttpStatus.CONFLICT),
  INVITATION_TYPE_MISMATCH(HttpStatus.BAD_REQUEST);

  private final HttpStatus status;

}
