package com.schemafy.api.erd.service.util.mysql;

import java.time.Instant;
import java.util.List;

import org.springframework.stereotype.Component;

import com.schemafy.api.erd.controller.dto.response.SchemaResponse;
import com.schemafy.api.erd.controller.dto.response.TableSnapshotResponse;
import com.schemafy.api.erd.service.util.DdlGenerator;

import lombok.RequiredArgsConstructor;

import static com.schemafy.api.erd.service.util.mysql.MySqlDdlUtils.normalizeTables;

@Component
@RequiredArgsConstructor
public class MySqlDdlGenerator implements DdlGenerator {

  private final MySqlCreateTableGenerator createTableGenerator;
  private final MySqlAlterTableGenerator alterTableGenerator;

  @Override
  public String generateSchemaDdl(SchemaResponse schema,
      List<TableSnapshotResponse> tables) {
    StringBuilder ddl = new StringBuilder();
    ddl.append(generateHeader(schema));

    List<TableSnapshotResponse> safeTables = normalizeTables(tables);

    for (TableSnapshotResponse table : safeTables) {
      ddl.append(createTableGenerator.generate(table));
      ddl.append("\n\n");
    }

    ddl.append(alterTableGenerator.generate(safeTables));

    return ddl.toString();
  }

  private String generateHeader(SchemaResponse schema) {
    String schemaName = escapeComment(schema.name());
    return "-- =============================================================================\n"
        + "-- Schema: " + schemaName + "\n"
        + "-- Exported: " + Instant.now() + "\n"
        + "-- Generated by Schemafy Export\n"
        + "-- =============================================================================\n\n";
  }

  private String escapeComment(String value) {
    if (value == null) {
      return "";
    }
    return value.replace("--", "- -").replace("\n", " ").replace("\r", " ");
  }

}
